DECLARE @TB_LUONG FLOAT
SET @TB_LUONG = (SELECT AVG(LUONG) FROM NHANVIEN)
----TRA KET QUA = NGHIENCUU---
SELECT HONV +' '+ TENLOT + TENNV as 'HỌ VÀ TÊN', LUONG,TENPHG
FROM NHANVIEN, PHONGBAN
WHERE LUONG >@TB_LUONG AND TENPHG=N'Nghiên cứu' and PHG =5