DECLARE @TB_LUONG FLOAT
SET @TB_LUONG = (SELECT AVG(LUONG) FROM NHANVIEN)
-----TB_LUONG>30000----
SELECT TENPHG as 'Tên Phòng',COUNT(*) as 'Số lượng nhân viên ở phòng ban:'
	FROM PHONGBAN,NHANVIEN
	WHERE MAPHG=PHG
	GROUP BY TENPHG
	HAVING @TB_LUONG>30000